### ISSUE TITLE
[ Request ] Timeout proses

### ISSUE THREAD

**Issue by berthojoris** [erikarenhill/Lightweight-JSONP#3]
Is it possible to add a function to define their own timeout of the callbacks?

When a process we can decide for yourself how much time will be needed in the process

**Comment by derwaldgeist** [comment]
I would need this too.

**Comment by erikarenhill** [comment]
Hey @derwaldgeist and @berthojoris and sorry for my inactivity in the project.
I just merged timeout functionality into master, feel free to try it out.

You'll just pass a timeout to init/config in milliseconds and it'll call the error handler after that time if it has not yet loaded.

The request will still load until browser/server- timeout, but the complete callback will not be called if it did timeout. No way to abort a started script load what I know of.
